/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Inventec.Common.LocalStorage.SdaConfig
{
    public partial class ConfigKeys
    {
        public const string DBCODE__BOS_RS__BOS_CUSTOMER_TYPE__CUSTOMER_TYPE_CODE__ENTERPRISE = "DBCODE.BOS_RS.BOS_CUSTOMER_TYPE.CUSTOMER_TYPE_CODE.ENTERPRISE";//
        public const string DBCODE__BOS_RS__BOS_CUSTOMER_TYPE__CUSTOMER_TYPE_CODE__INDIVIDUAL = "DBCODE.BOS_RS.BOS_CUSTOMER_TYPE.CUSTOMER_TYPE_CODE.INDIVIDUAL";//
        public const string DBCODE__BOS_RS__BOS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__DEPOSIT = "DBCODE.BOS_RS.BOS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.DEPOSIT";//
        public const string DBCODE__BOS_RS__BOS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__TRANSFER = "DBCODE.BOS_RS.BOS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.TRANSFER";//
        public const string DBCODE__BOS_RS__BOS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__WITHDRAW = "DBCODE.BOS_RS.BOS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.WITHDRAW";//
        public const string DBCODE__COS_RS__COS_CARD_STT__CARD_STT_CODE__ISSUE = "DBCODE.COS_RS.COS_CARD_STT.CARD_STT_CODE.ISSUE";//
        public const string DBCODE__COS_RS__COS_CARD_STT__CARD_STT_CODE__RAW = "DBCODE.COS_RS.COS_CARD_STT.CARD_STT_CODE.RAW";//
        public const string DBCODE__COS_RS__COS_CARD_STT__CARD_STT_CODE__WHITE = "DBCODE.COS_RS.COS_CARD_STT.CARD_STT_CODE.WHITE";//
        public const string DBCODE__COS_RS__COS_GENDER__GENDER_CODE__FEMALE = "DBCODE.COS_RS.COS_GENDER.GENDER_CODE.FEMALE";//
        public const string DBCODE__COS_RS__COS_GENDER__GENDER_CODE__MALE = "DBCODE.COS_RS.COS_GENDER.GENDER_CODE.MALE";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__ANESTHETIST = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.ANESTHETIST";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__ANESTHETIST_ASSIST = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.ANESTHETIST_ASSIST";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__DRESSER = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.DRESSER";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__INSTRUMENT = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.INSTRUMENT";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__MAIN = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.MAIN";//
        public const string DBCODE__HIS_RS__HIS_EXECUTE_ROLE__EXECUTE_ROLE_CODE__NURSE = "DBCODE.HIS_RS.HIS_EXECUTE_ROLE.EXECUTE_ROLE_CODE.NURSE";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__AGGREGATE = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.AGGREGATE";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__APPROVED = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.APPROVED";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__DRAFT = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.DRAFT";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__EXPORTED = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.EXPORTED";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__REJECTED = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.REJECTED";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_STT__EXP_MEST_STT_CODE__REQUEST = "DBCODE.HIS_RS.HIS_EXP_MEST_STT.EXP_MEST_STT_CODE.REQUEST";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__AGGR = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.AGGR";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__CHMS = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.CHMS";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__DEPA = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.DEPA";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__EXPE = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.EXPE";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__LIQU = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.LIQU";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__LOST = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.LOST";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__MANU = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.MANU";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__OTHER = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.OTHER";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__PRES = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.PRES";//
        public const string DBCODE__HIS_RS__HIS_EXP_MEST_TYPE__EXP_MEST_TYPE_CODE__SALE = "DBCODE.HIS_RS.HIS_EXP_MEST_TYPE.EXP_MEST_TYPE_CODE.SALE";//
        public const string DBCODE__HIS_RS__HIS_GENDER__GENDER_CODE__FEMALE = "DBCODE.HIS_RS.HIS_GENDER.GENDER_CODE.FEMALE";//
        public const string DBCODE__HIS_RS__HIS_GENDER__GENDER_CODE__MALE = "DBCODE.HIS_RS.HIS_GENDER.GENDER_CODE.MALE";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_STT__IMP_MEST_STT_CODE__APPROVED = "DBCODE.HIS_RS.HIS_IMP_MEST_STT.IMP_MEST_STT_CODE.APPROVED";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_STT__IMP_MEST_STT_CODE__DRAFT = "DBCODE.HIS_RS.HIS_IMP_MEST_STT.IMP_MEST_STT_CODE.DRAFT";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_STT__IMP_MEST_STT_CODE__IMPORTED = "DBCODE.HIS_RS.HIS_IMP_MEST_STT.IMP_MEST_STT_CODE.IMPORTED";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_STT__IMP_MEST_STT_CODE__REJECTED = "DBCODE.HIS_RS.HIS_IMP_MEST_STT.IMP_MEST_STT_CODE.REJECTED";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_STT__IMP_MEST_STT_CODE__REQUEST = "DBCODE.HIS_RS.HIS_IMP_MEST_STT.IMP_MEST_STT_CODE.REQUEST";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__AGGR = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.AGGR";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__CHMS = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.CHMS";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__GIBA = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.GIBA";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__INIT = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.INIT";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__INVE = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.INVE";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__MANU = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.MANU";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__MOBA = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.MOBA";//
        public const string DBCODE__HIS_RS__HIS_IMP_MEST_TYPE__IMP_MEST_TYPE_CODE__OTHER = "DBCODE.HIS_RS.HIS_IMP_MEST_TYPE.IMP_MEST_TYPE_CODE.OTHER";//
        public const string DBCODE__HIS_RS__HIS_INFUSION_STT__INFUSION_STT_CODE__FINISH = "DBCODE.HIS_RS.HIS_INFUSION_STT.INFUSION_STT_CODE.FINISH";//
        public const string DBCODE__HIS_RS__HIS_INFUSION_STT__INFUSION_STT_CODE__REQUEST = "DBCODE.HIS_RS.HIS_INFUSION_STT.INFUSION_STT_CODE.REQUEST";//Cấu hình tuyến của bệnh viện đang sử dụng phần mềm- 1: trung ương- 2: tỉnh- 3: huyện- 4: xã"
        public const string DBCODE__HIS_RS__HIS_MEDICINE_LINE__MEDICINE_LINE_CODE__CPYHCT = "DBCODE.HIS_RS.HIS_MEDICINE_LINE.MEDICINE_LINE_CODE.CPYHCT";//Danh sách các mã nơi ĐKKCB ban đầu mà bệnh viện chấp nhận đúng tuyến
        public const string DBCODE__HIS_RS__HIS_MEDICINE_LINE__MEDICINE_LINE_CODE__GENERIC = "DBCODE.HIS_RS.HIS_MEDICINE_LINE.MEDICINE_LINE_CODE.GENERIC";//Mã nơi ĐKKCB ban đầu của bệnh viện sử dụng phần mềm
        public const string DBCODE__HIS_RS__HIS_MEDICINE_LINE__MEDICINE_LINE_CODE__VTYHCT = "DBCODE.HIS_RS.HIS_MEDICINE_LINE.MEDICINE_LINE_CODE.VTYHCT";//
        public const string DBCODE__HIS_RS__HIS_MEDI_REACT_STT__MEDI_REACT_STT_CODE__CHECKED = "DBCODE.HIS_RS.HIS_MEDI_REACT_STT.MEDI_REACT_STT_CODE.CHECKED";//
        public const string DBCODE__HIS_RS__HIS_MEDI_REACT_STT__MEDI_REACT_STT_CODE__DONE = "DBCODE.HIS_RS.HIS_MEDI_REACT_STT.MEDI_REACT_STT_CODE.DONE";//
        public const string DBCODE__HIS_RS__HIS_MEDI_REACT_STT__MEDI_REACT_STT_CODE__REQ = "DBCODE.HIS_RS.HIS_MEDI_REACT_STT.MEDI_REACT_STT_CODE.REQ";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__AIA = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.AIA";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__BCV = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.BCV";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__BHYT = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.BHYT";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__BIC = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.BIC";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__BVTM = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.BVTM";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__DAIICHI = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.DAIICHI";//Chuyển người bệnh từ tuyến dưới lên tuyến trên liền kề
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__GEL = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.GEL";//Chuyển người bệnh từ tuyến dưới lên tuyến trên không qua tuyến liền kề
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__GENERALI = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.GENERALI";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__INSMART = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.INSMART";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__KSK = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.KSK";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__LIBERTY = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.LIBERTY";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__PRUD = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.PRUD";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__PTI = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.PTI";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__PVI = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.PVI";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__TMN = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.TMN";//
        public const string DBCODE__HIS_RS__HIS_PATIENT_TYPE__PATIENT_TYPE_CODE__VCLI = "DBCODE.HIS_RS.HIS_PATIENT_TYPE.PATIENT_TYPE_CODE.VCLI";//
        public const string DBCODE__HIS_RS__HIS_RIGHT_ROUTE_TYPE__RIGHT_ROUTE_TYPE_CODE__DTCC = "DBCODE.HIS_RS.HIS_RIGHT_ROUTE_TYPE.RIGHT_ROUTE_TYPE_CODE.DTCC";//bệnh nhân BHYT
        public const string DBCODE__HIS_RS__HIS_RIGHT_ROUTE_TYPE__RIGHT_ROUTE_TYPE_CODE__DTGT = "DBCODE.HIS_RS.HIS_RIGHT_ROUTE_TYPE.RIGHT_ROUTE_TYPE_CODE.DTGT";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__BED = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.BED";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__CASHIER = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.CASHIER";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__EXECUTE = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.EXECUTE";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__RECEPTION = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.RECEPTION";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__SAMPLE = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.SAMPLE";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__STOCK = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.STOCK";//
        public const string DBCODE__HIS_RS__HIS_ROOM_TYPE__ROOM_TYPE_CODE__STORE = "DBCODE.HIS_RS.HIS_ROOM_TYPE.ROOM_TYPE_CODE.STORE";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_STT__SERVICE_REQ_STT_CODE__FINISH = "DBCODE.HIS_RS.HIS_SERVICE_REQ_STT.SERVICE_REQ_STT_CODE.FINISH";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_STT__SERVICE_REQ_STT_CODE__INPROCESS = "DBCODE.HIS_RS.HIS_SERVICE_REQ_STT.SERVICE_REQ_STT_CODE.INPROCESS";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_STT__SERVICE_REQ_STT_CODE__NEW = "DBCODE.HIS_RS.HIS_SERVICE_REQ_STT.SERVICE_REQ_STT_CODE.NEW";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__BED = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.BED";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__DIIM = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.DIIM";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__ENDO = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.ENDO";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__EXAM = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.EXAM";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__FUEX = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.FUEX";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__MISU = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.MISU";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__OTHER = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.OTHER";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__PRES = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.PRES";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__REHA = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.REHA";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__SUIM = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.SUIM";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__SURG = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.SURG";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_REQ_TYPE__SERVICE_REQ_TYPE_CODE__TEST = "DBCODE.HIS_RS.HIS_SERVICE_REQ_TYPE.SERVICE_REQ_TYPE_CODE.TEST";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__BED = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.BED";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__DIIM = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.DIIM";//Mã của ứng dụng HIS do Roche cung cấp
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__ENDO = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.ENDO";//Mã của hệ thống LIS của Roche do Roche cung cấp
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__EXAM = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.EXAM";//+ 1: nếu hệ thống có tích hợp hệ thống LIS của Roche+ Khác 1: nếu hệ thống có tích hợp hệ thống LIS của Roche"
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__FUEX = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.FUEX";//Đối tượng miễn phí
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__MATE = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.MATE";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__MEDI = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.MEDI";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__MISU = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.MISU";//Đường dùng của thuốc truyền dịch
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__OTHER = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.OTHER";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__REHA = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.REHA";//DVT của thuốc truyền dịch
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__SUIM = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.SUIM";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__SURG = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.SURG";//
        public const string DBCODE__HIS_RS__HIS_SERVICE_TYPE__SERVICE_TYPE_CODE__TEST = "DBCODE.HIS_RS.HIS_SERVICE_TYPE.SERVICE_TYPE_CODE.TEST";//
        public const string DBCODE__HIS_RS__HIS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__BILL = "DBCODE.HIS_RS.HIS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.BILL";//
        public const string DBCODE__HIS_RS__HIS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__DEPOSIT = "DBCODE.HIS_RS.HIS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.DEPOSIT";//
        public const string DBCODE__HIS_RS__HIS_TRANSACTION_TYPE__TRANSACTION_TYPE_CODE__REPAY = "DBCODE.HIS_RS.HIS_TRANSACTION_TYPE.TRANSACTION_TYPE_CODE.REPAY";//
        public const string DBCODE__HIS_RS__HIS_TRAN_PATI_TYPE__TRAN_PATI_TYPE_CODE__IN = "DBCODE.HIS_RS.HIS_TRAN_PATI_TYPE.TRAN_PATI_TYPE_CODE.IN";//
        public const string DBCODE__HIS_RS__HIS_TRAN_PATI_TYPE__TRAN_PATI_TYPE_CODE__OUT = "DBCODE.HIS_RS.HIS_TRAN_PATI_TYPE.TRAN_PATI_TYPE_CODE.OUT";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_END_TYPE__TREATMENT_END_TYPE_CODE__DEATH = "DBCODE.HIS_RS.HIS_TREATMENT_END_TYPE.TREATMENT_END_TYPE_CODE.DEATH";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_END_TYPE__TREATMENT_END_TYPE_CODE__TRAN_PATI = "DBCODE.HIS_RS.HIS_TREATMENT_END_TYPE.TREATMENT_END_TYPE_CODE.TRAN_PATI";//Bệnh nhân viện phí
        public const string DBCODE__HIS_RS__HIS_TREATMENT_LOG_TYPE__TREATMENT_LOG_TYPE_CODE__DEPARTMENT_TRAN = "DBCODE.HIS_RS.HIS_TREATMENT_LOG_TYPE.TREATMENT_LOG_TYPE_CODE.DEPARTMENT_TRAN";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_LOG_TYPE__TREATMENT_LOG_TYPE_CODE__MEDI_RECORD = "DBCODE.HIS_RS.HIS_TREATMENT_LOG_TYPE.TREATMENT_LOG_TYPE_CODE.MEDI_RECORD";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_LOG_TYPE__TREATMENT_LOG_TYPE_CODE__PATIENT_TYPE_ALTER = "DBCODE.HIS_RS.HIS_TREATMENT_LOG_TYPE.TREATMENT_LOG_TYPE_CODE.PATIENT_TYPE_ALTER";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_TYPE__TREATMENT_TYPE_CODE__EXAM = "DBCODE.HIS_RS.HIS_TREATMENT_TYPE.TREATMENT_TYPE_CODE.EXAM";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_TYPE__TREATMENT_TYPE_CODE__IN = "DBCODE.HIS_RS.HIS_TREATMENT_TYPE.TREATMENT_TYPE_CODE.IN";//
        public const string DBCODE__HIS_RS__HIS_TREATMENT_TYPE__TREATMENT_TYPE_CODE__OUT = "DBCODE.HIS_RS.HIS_TREATMENT_TYPE.TREATMENT_TYPE_CODE.OUT";//
        public const string DBCODE__SAR_RS__SAR_REPORT_STT__REPORT_STT_CODE__CANCEL = "DBCODE.SAR_RS.SAR_REPORT_STT.REPORT_STT_CODE.CANCEL";//
        public const string DBCODE__SAR_RS__SAR_REPORT_STT__REPORT_STT_CODE__DONE = "DBCODE.SAR_RS.SAR_REPORT_STT.REPORT_STT_CODE.DONE";//
        public const string DBCODE__SAR_RS__SAR_REPORT_STT__REPORT_STT_CODE__ERROR = "DBCODE.SAR_RS.SAR_REPORT_STT.REPORT_STT_CODE.ERROR";//
        public const string DBCODE__SAR_RS__SAR_REPORT_STT__REPORT_STT_CODE__PROCESSING = "DBCODE.SAR_RS.SAR_REPORT_STT.REPORT_STT_CODE.PROCESSING";//
        public const string DBCODE__SAR_RS__SAR_REPORT_STT__REPORT_STT_CODE__WAIT = "DBCODE.SAR_RS.SAR_REPORT_STT.REPORT_STT_CODE.WAIT";//
        public const string DBCODE__SMS_RS__SMS_MO_STT__MO_STT_CODE__FAIL = "DBCODE.SMS_RS.SMS_MO_STT.MO_STT_CODE.FAIL";//
        public const string DBCODE__SMS_RS__SMS_MO_STT__MO_STT_CODE__RECEIVE = "DBCODE.SMS_RS.SMS_MO_STT.MO_STT_CODE.RECEIVE";//
        public const string DBCODE__SMS_RS__SMS_MO_STT__MO_STT_CODE__SUCCESS = "DBCODE.SMS_RS.SMS_MO_STT.MO_STT_CODE.SUCCESS";//
        public const string DBCODE__SMS_RS__SMS_MT_STT__MT_STT_CODE__FAIL = "DBCODE.SMS_RS.SMS_MT_STT.MT_STT_CODE.FAIL";//
        public const string DBCODE__SMS_RS__SMS_MT_STT__MT_STT_CODE__RECEIVE = "DBCODE.SMS_RS.SMS_MT_STT.MT_STT_CODE.RECEIVE";//
        public const string DBCODE__SMS_RS__SMS_MT_STT__MT_STT_CODE__SUCCESS = "DBCODE.SMS_RS.SMS_MT_STT.MT_STT_CODE.SUCCESS";//- 1: nếu muốn hiển thị nhóm còn lại (không xác định)"
    }
}
