/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.UC.Login.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.UC.Login.Message.MessageViResource", typeof(MessageViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thành công.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThanhCong {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thất bại.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc bị hết hiệu lực, có thể do bạn đã ngừng sử dụng phần mềm trong một khoảng thời gian dài hoặc kết nối đến hệ thống máy chủ bị gián đoạn tạm thời. Phần mềm sẽ tự động đăng xuất. Vui lòng đăng nhập lại để tiếp tục sử dụng..
        /// </summary>
        internal static string HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai {
            get {
                return ResourceManager.GetString("HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thất bại. Vui lòng liên hệ với quản trị hệ thống để được hỗ trợ.
        /// </summary>
        internal static string HeThongTBXuatHienExceptionChuaKiemDuocSoat {
            get {
                return ResourceManager.GetString("HeThongTBXuatHienExceptionChuaKiemDuocSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý, vui lòng đợi....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%....
        /// </summary>
        internal static string HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong {
            get {
                return ResourceManager.GetString("HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn chi nhánh làm việc.
        /// </summary>
        internal static string NguoiDungChuaChonChiNhanh {
            get {
                return ResourceManager.GetString("NguoiDungChuaChonChiNhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu.
        /// </summary>
        internal static string NguoiDungChuaNhapMatKhauDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapMatKhauDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tài khoản.
        /// </summary>
        internal static string NguoiDungChuaNhapTaiKhoanDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapTaiKhoanDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần mềm không kết nối được tới máy chủ hệ thống. Vui lòng kiểm tra lại cấu hình và kết nối.
        /// </summary>
        internal static string PhanMemKhongKetNoiDuocToiMayChuHeThong {
            get {
                return ResourceManager.GetString("PhanMemKhongKetNoiDuocToiMayChuHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thiếu thông tin bắt buộc.
        /// </summary>
        internal static string ThieuTruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("ThieuTruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaCanhBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaLoi {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaThongBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string TieuDeThongTinHienThiPhanTrang {
            get {
                return ResourceManager.GetString("TieuDeThongTinHienThiPhanTrang", resourceCulture);
            }
        }
    }
}
