/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.UC.Login.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageMyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageMyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.UC.Login.Message.MessageMyResource", typeof(MessageMyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လုပ်ငန်းစဉ် အောင်မြင်ပါသည်။.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThanhCong {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လုပ်ငန်းစဉ်မအောင်မြင်.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသုံးပြုသူ ဆုံးရှုံးသွားသော စက်ရှင်ဆာဗာ၊ ကျေးဇူးပြု၍ အကောင့်ဝင်ရန် ထပ်မံကြိုးစားပါ။.
        /// </summary>
        internal static string HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai {
            get {
                return ResourceManager.GetString("HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခြွင်းချက်ရှိသည်။ ပံ့ပိုးကူညီမှုအတွက် စနစ်စီမံခန့်ခွဲသူထံ ဆက်သွယ်ပါ။.
        /// </summary>
        internal static string HeThongTBXuatHienExceptionChuaKiemDuocSoat {
            get {
                return ResourceManager.GetString("HeThongTBXuatHienExceptionChuaKiemDuocSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လုပ်ဆောင်နေသည်၊ ကျေးဇူးပြု၍ စောင့်ပါ....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%....
        /// </summary>
        internal static string HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong {
            get {
                return ResourceManager.GetString("HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကြောင်းကြားပါ။.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NguoiDungChuaChonChiNhanh {
            get {
                return ResourceManager.GetString("NguoiDungChuaChonChiNhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စကားဝှက် လိုအပ်သည်။.
        /// </summary>
        internal static string NguoiDungChuaNhapMatKhauDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapMatKhauDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကောင့်လိုအပ်ပါသည်။.
        /// </summary>
        internal static string NguoiDungChuaNhapTaiKhoanDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapTaiKhoanDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကောင့် သို့မဟုတ် စကားဝှက် မမှန်ကန်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆော့ဖ်ဝဲသည် ဆာဗာသို့ ချိတ်ဆက်၍မရပါ။ ကျေးဇူးပြု၍ config နှင့် network ကိုစစ်ဆေးပါ။.
        /// </summary>
        internal static string PhanMemKhongKetNoiDuocToiMayChuHeThong {
            get {
                return ResourceManager.GetString("PhanMemKhongKetNoiDuocToiMayChuHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null မဟုတ်ပါ။.
        /// </summary>
        internal static string ThieuTruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("ThieuTruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတိပေးပါ။.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaCanhBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အမှား.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaLoi {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကြောင်းကြားပါ။.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaThongBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စာမျက်နှာ.
        /// </summary>
        internal static string TieuDeThongTinHienThiPhanTrang {
            get {
                return ResourceManager.GetString("TieuDeThongTinHienThiPhanTrang", resourceCulture);
            }
        }
    }
}
