/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Desktop.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Desktop.Core.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AlertFilterAll {
            get {
                return ResourceManager.GetString("AlertFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and Warnings.
        /// </summary>
        internal static string AlertFilterErrorsAndWarnings {
            get {
                return ResourceManager.GetString("AlertFilterErrorsAndWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors only.
        /// </summary>
        internal static string AlertFilterErrorsOnly {
            get {
                return ResourceManager.GetString("AlertFilterErrorsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string ColumnLevel {
            get {
                return ResourceManager.GetString("ColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ColumnMessage {
            get {
                return ResourceManager.GetString("ColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ColumnTime {
            get {
                return ResourceManager.GetString("ColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string ColumnWorkspace {
            get {
                return ResourceManager.GetString("ColumnWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Theme.
        /// </summary>
        internal static string DescriptionDefaultTheme {
            get {
                return ResourceManager.GetString("DescriptionDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures global exception handling behaviour..
        /// </summary>
        internal static string DescriptionExceptionHandlerSettings {
            get {
                return ResourceManager.GetString("DescriptionExceptionHandlerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows configuration of display format of common items such as dates, times, etc..
        /// </summary>
        internal static string DescriptionFormatSettings {
            get {
                return ResourceManager.GetString("DescriptionFormatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event {0} does not exist for class {1}..
        /// </summary>
        internal static string ExceptionActionBuilderEventDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderEventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} does not exist for class {1}, or it does not have the correct signature..
        /// </summary>
        internal static string ExceptionActionBuilderMethodDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderMethodDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} does not exist for class {1}, or it does not have the correct return type..
        /// </summary>
        internal static string ExceptionActionBuilderPropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} on class {1} does not have a public get method..
        /// </summary>
        internal static string ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the active workspace to null..
        /// </summary>
        internal static string ExceptionActiveWorkspaceCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionActiveWorkspaceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve application root class {0} - multiple matches..
        /// </summary>
        internal static string ExceptionApplicationRootMultipleMatches {
            get {
                return ResourceManager.GetString("ExceptionApplicationRootMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve application root class {0} - no matches..
        /// </summary>
        internal static string ExceptionApplicationRootNoMatches {
            get {
                return ResourceManager.GetString("ExceptionApplicationRootNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non-negative..
        /// </summary>
        internal static string ExceptionArgumentNegative {
            get {
                return ResourceManager.GetString("ExceptionArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        internal static string ExceptionArgumentNotPositive {
            get {
                return ResourceManager.GetString("ExceptionArgumentNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} = {0} is invalid. {3} must be &gt;= {1} and &lt;= {2}..
        /// </summary>
        internal static string ExceptionArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An AssociateViewAttribute must be specified for the input Type in order to create the Associated View..
        /// </summary>
        internal static string ExceptionAssociateViewAttributeNotSpecified {
            get {
                return ResourceManager.GetString("ExceptionAssociateViewAttributeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background task is already running.
        /// </summary>
        internal static string ExceptionBackgroundTaskAlreadyRunning {
            get {
                return ResourceManager.GetString("ExceptionBackgroundTaskAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load exception dialog settings - defaulting to detailed view.
        /// </summary>
        internal static string ExceptionCannotLoadExceptionDialogSetting {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadExceptionDialogSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set pane after container has been started..
        /// </summary>
        internal static string ExceptionCannotSetPaneAfterContainerStarted {
            get {
                return ResourceManager.GetString("ExceptionCannotSetPaneAfterContainerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to Array, ICollection, or IEnumerable type..
        /// </summary>
        internal static string ExceptionCastExpressionArrayCollectionEnumerable {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionArrayCollectionEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to Boolean type..
        /// </summary>
        internal static string ExceptionCastExpressionBoolean {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to IEnumerable type..
        /// </summary>
        internal static string ExceptionCastExpressionEnumerable {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to String type..
        /// </summary>
        internal static string ExceptionCastExpressionString {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has already been started..
        /// </summary>
        internal static string ExceptionComponentAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component was never started, or has already been stopped..
        /// </summary>
        internal static string ExceptionComponentNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition is not met :{0}.
        /// </summary>
        internal static string ExceptionConditionIsNotMet {
            get {
                return ResourceManager.GetString("ExceptionConditionIsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container has already been started.
        /// </summary>
        internal static string ExceptionContainerAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container was never started, or has already been stopped..
        /// </summary>
        internal static string ExceptionContainerNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main desktop view has not been created..
        /// </summary>
        internal static string ExceptionDesktopViewNotCreated {
            get {
                return ResourceManager.GetString("ExceptionDesktopViewNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate plugin {0} found..
        /// </summary>
        internal static string ExceptionDuplicatePluginFound {
            get {
                return ResourceManager.GetString("ExceptionDuplicatePluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string ExceptionEmptyString {
            get {
                return ResourceManager.GetString("ExceptionEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type {0}..
        /// </summary>
        internal static string ExceptionExpectedType {
            get {
                return ResourceManager.GetString("ExceptionExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} does not extend a valid extension point class..
        /// </summary>
        internal static string ExceptionExtensionDoesNotExtendValidExtensionPointClass {
            get {
                return ResourceManager.GetString("ExceptionExtensionDoesNotExtendValidExtensionPointClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} does not implement required interface {1}..
        /// </summary>
        internal static string ExceptionExtensionDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("ExceptionExtensionDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} must be a concrete class..
        /// </summary>
        internal static string ExceptionExtensionMustBeConcreteClass {
            get {
                return ResourceManager.GetString("ExceptionExtensionMustBeConcreteClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension point {0} is invalid because it is not a direct subclass of ExtensionPoint&lt;&gt;.
        /// </summary>
        internal static string ExceptionExtensionPointMustSubclassExtensionPoint {
            get {
                return ResourceManager.GetString("ExceptionExtensionPointMustSubclassExtensionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to save changes to this item.
        /// </summary>
        internal static string ExceptionFailedToSave {
            get {
                return ResourceManager.GetString("ExceptionFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer file from {0} to {1}..
        /// </summary>
        internal static string ExceptionFailedToTransferFile {
            get {
                return ResourceManager.GetString("ExceptionFailedToTransferFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but an error has occurred that ClearCanvas Workstation cannot recover from.  Please check the log and restart..
        /// </summary>
        internal static string ExceptionFatalApplicationError {
            get {
                return ResourceManager.GetString("ExceptionFatalApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from String to {0}.
        /// </summary>
        internal static string ExceptionFormatCannotConvertFromStringToType {
            get {
                return ResourceManager.GetString("ExceptionFormatCannotConvertFromStringToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from {0} to String.
        /// </summary>
        internal static string ExceptionFormatCannotConvertFromTypeToString {
            get {
                return ResourceManager.GetString("ExceptionFormatCannotConvertFromTypeToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization failed for object type &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionFormatDeserializationFailedForType {
            get {
                return ResourceManager.GetString("ExceptionFormatDeserializationFailedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization failed for object type &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionFormatSerializationFailedForType {
            get {
                return ResourceManager.GetString("ExceptionFormatSerializationFailedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}[{0}] is invalid.  Index must be &gt;= {1} and &lt;= {2}..
        /// </summary>
        internal static string ExceptionIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExceptionInvalidActionPath {
            get {
                return ResourceManager.GetString("ExceptionInvalidActionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action path.  Path must have 2 or more segments..
        /// </summary>
        internal static string ExceptionInvalidActionPath1 {
            get {
                return ResourceManager.GetString("ExceptionInvalidActionPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be of type {1}..
        /// </summary>
        internal static string ExceptionInvalidCast {
            get {
                return ResourceManager.GetString("ExceptionInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid specification id..
        /// </summary>
        internal static string ExceptionInvalidSpecificationId {
            get {
                return ResourceManager.GetString("ExceptionInvalidSpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JScript evaluation error on {0}: {1}.
        /// </summary>
        internal static string ExceptionJScriptEvaluation {
            get {
                return ResourceManager.GetString("ExceptionJScriptEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been set.  Object state is invalid..
        /// </summary>
        internal static string ExceptionMemberNotSet {
            get {
                return ResourceManager.GetString("ExceptionMemberNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been set.  {1}.
        /// </summary>
        internal static string ExceptionMemberNotSetVerbose {
            get {
                return ResourceManager.GetString("ExceptionMemberNotSetVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one model plugin found..
        /// </summary>
        internal static string ExceptionMoreThanOneModelPluginFound {
            get {
                return ResourceManager.GetString("ExceptionMoreThanOneModelPluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extensions found for extension point {0}, or the extensions could not be instantiated.  Please see the log for more information..
        /// </summary>
        internal static string ExceptionNoExtensionsCreated {
            get {
                return ResourceManager.GetString("ExceptionNoExtensionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins could be found..
        /// </summary>
        internal static string ExceptionNoPluginsFound {
            get {
                return ResourceManager.GetString("ExceptionNoPluginsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins have been loaded..
        /// </summary>
        internal static string ExceptionNoPluginsLoaded {
            get {
                return ResourceManager.GetString("ExceptionNoPluginsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} is not a plugin..
        /// </summary>
        internal static string ExceptionNotAPlugin {
            get {
                return ResourceManager.GetString("ExceptionNotAPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection already contains this object.
        /// </summary>
        internal static string ExceptionObjectAlreadyInCollection {
            get {
                return ResourceManager.GetString("ExceptionObjectAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with the name {0} already exists.
        /// </summary>
        internal static string ExceptionObjectWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionObjectWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string ExceptionPathDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} could not be found.  Unable to start plugin..
        /// </summary>
        internal static string ExceptionPluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("ExceptionPluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory could not be found..
        /// </summary>
        internal static string ExceptionPluginDirectoryNotFound {
            get {
                return ResourceManager.GetString("ExceptionPluginDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading one or more plugins. Please see the log for more information..
        /// </summary>
        internal static string ExceptionPluginWarning {
            get {
                return ResourceManager.GetString("ExceptionPluginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference property must be of same type as validating property..
        /// </summary>
        internal static string ExceptionReferencePropertyMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferencePropertyMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference value must be of same type as validating property..
        /// </summary>
        internal static string ExceptionReferenceValueMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferenceValueMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0}  not found..
        /// </summary>
        internal static string ExceptionResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script engine available for language {0}..
        /// </summary>
        internal static string ExceptionScriptEngineLanguage {
            get {
                return ResourceManager.GetString("ExceptionScriptEngineLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component cannot exit because it is not at the top of the component stack..
        /// </summary>
        internal static string ExceptionStackComponentCannotExit {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pop - component stack is empty..
        /// </summary>
        internal static string ExceptionStackComponentCannotPop {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column must be added to a table to determine its percentage width..
        /// </summary>
        internal static string ExceptionTableColumnMustBeAddedToDetermineWidth {
            get {
                return ResourceManager.GetString("ExceptionTableColumnMustBeAddedToDetermineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table item not found in collection..
        /// </summary>
        internal static string ExceptionTableItemNotFoundInCollection {
            get {
                return ResourceManager.GetString("ExceptionTableItemNotFoundInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template evaluation generated an exception..
        /// </summary>
        internal static string ExceptionTemplateEvaluation {
            get {
                return ResourceManager.GetString("ExceptionTemplateEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool has already been started..
        /// </summary>
        internal static string ExceptionThreadPoolAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool must be stopped before setting the {0} parameter..
        /// </summary>
        internal static string ExceptionThreadPoolMustBeStopped {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolMustBeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool has not been started.  Unable to enqueue the specified item..
        /// </summary>
        internal static string ExceptionThreadPoolNotStarted {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown.
        /// </summary>
        internal static string ExceptionThrown {
            get {
                return ResourceManager.GetString("ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load any plugins.  Please see the log for more information..
        /// </summary>
        internal static string ExceptionUnableToLoadPlugins {
            get {
                return ResourceManager.GetString("ExceptionUnableToLoadPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration upgrades are performed by the LocalFileSettingsProvider included in the .NET framework..
        /// </summary>
        internal static string ExceptionUpgradeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionUpgradeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attribute cannot be applied to property of type {1}..
        /// </summary>
        internal static string FormatAttributeCannotBeAppliedToPropertyType {
            get {
                return ResourceManager.GetString("FormatAttributeCannotBeAppliedToPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days from now.
        /// </summary>
        internal static string FormatDateInFutureDays {
            get {
                return ResourceManager.GetString("FormatDateInFutureDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string FormatDateInPastDays {
            get {
                return ResourceManager.GetString("FormatDateInPastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string FormatDesktopWindowTitle {
            get {
                return ResourceManager.GetString("FormatDesktopWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes.
        /// </summary>
        internal static string FormatFileSizeBytes {
            get {
                return ResourceManager.GetString("FormatFileSizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} GB.
        /// </summary>
        internal static string FormatFileSizeGB {
            get {
                return ResourceManager.GetString("FormatFileSizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} KB.
        /// </summary>
        internal static string FormatFileSizeKB {
            get {
                return ResourceManager.GetString("FormatFileSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} MB.
        /// </summary>
        internal static string FormatFileSizeMB {
            get {
                return ResourceManager.GetString("FormatFileSizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} TB.
        /// </summary>
        internal static string FormatFileSizeTB {
            get {
                return ResourceManager.GetString("FormatFileSizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin: {0}.
        /// </summary>
        internal static string FormatLoadedPlugin {
            get {
                return ResourceManager.GetString("FormatLoadedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than {0} characters required.
        /// </summary>
        internal static string FormatMoreThanXCharactersRequired {
            get {
                return ResourceManager.GetString("FormatMoreThanXCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than {0}.
        /// </summary>
        internal static string FormatMustBeGreaterThan {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to {0}.
        /// </summary>
        internal static string FormatMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {0}.
        /// </summary>
        internal static string FormatMustBeLessThan {
            get {
                return ResourceManager.GetString("FormatMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than or equal to {0}.
        /// </summary>
        internal static string FormatMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing plugin: {0}.
        /// </summary>
        internal static string FormatProcessingPlugin {
            get {
                return ResourceManager.GetString("FormatProcessingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {0} and {1} characters required.
        /// </summary>
        internal static string FormatRangeCharactersRequired {
            get {
                return ResourceManager.GetString("FormatRangeCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string FormatReleaseType {
            get {
                return ResourceManager.GetString("FormatReleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string FormatSeconds {
            get {
                return ResourceManager.GetString("FormatSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today {0}.
        /// </summary>
        internal static string FormatTimeToday {
            get {
                return ResourceManager.GetString("FormatTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow {0}.
        /// </summary>
        internal static string FormatTimeTomorrow {
            get {
                return ResourceManager.GetString("FormatTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday {0}.
        /// </summary>
        internal static string FormatTimeYesterday {
            get {
                return ResourceManager.GetString("FormatTimeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated For {0} Days.
        /// </summary>
        internal static string FormatTotalDaysUsed {
            get {
                return ResourceManager.GetString("FormatTotalDaysUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be an interface..
        /// </summary>
        internal static string FormatTypeMustBeInterface {
            get {
                return ResourceManager.GetString("FormatTypeMustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must implement interface &apos;{1}&apos;..
        /// </summary>
        internal static string FormatTypeMustImplementInterface {
            get {
                return ResourceManager.GetString("FormatTypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find matching action for &apos;{0}&apos; node in script.  Unable to perform action..
        /// </summary>
        internal static string FormatUnableToFindMatchingAction {
            get {
                return ResourceManager.GetString("FormatUnableToFindMatchingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom date format must be from the available list..
        /// </summary>
        internal static string InvalidCustomDateFormat {
            get {
                return ResourceManager.GetString("InvalidCustomDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Actions.
        /// </summary>
        internal static string LabelAllActions {
            get {
                return ResourceManager.GetString("LabelAllActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Offline) Values shown may not be accurate, and changes may not be saved..
        /// </summary>
        internal static string LabelConfigurationWarningOffline {
            get {
                return ResourceManager.GetString("LabelConfigurationWarningOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        internal static string LabelEvaluation {
            get {
                return ResourceManager.GetString("LabelEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation ({0} days).
        /// </summary>
        internal static string LabelEvaluationWithDays {
            get {
                return ResourceManager.GetString("LabelEvaluationWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string LabelImport {
            get {
                return ResourceManager.GetString("LabelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string LabelLarge {
            get {
                return ResourceManager.GetString("LabelLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string LabelMedium {
            get {
                return ResourceManager.GetString("LabelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome.
        /// </summary>
        internal static string LabelMonochrome {
            get {
                return ResourceManager.GetString("LabelMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string LabelNewGroup {
            get {
                return ResourceManager.GetString("LabelNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not for Diagnostic Use.
        /// </summary>
        internal static string LabelNotForDiagnosticUse {
            get {
                return ResourceManager.GetString("LabelNotForDiagnosticUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not for Human Diagnosis.
        /// </summary>
        internal static string LabelNotForHumanDiagnosis {
            get {
                return ResourceManager.GetString("LabelNotForHumanDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string LabelReset {
            get {
                return ResourceManager.GetString("LabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string LabelResetAll {
            get {
                return ResourceManager.GetString("LabelResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        internal static string LabelSaveAll {
            get {
                return ResourceManager.GetString("LabelSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Separator).
        /// </summary>
        internal static string LabelSeparator {
            get {
                return ResourceManager.GetString("LabelSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string LabelSmall {
            get {
                return ResourceManager.GetString("LabelSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration store not found - defaulting to LocalFileSettingsProvider.
        /// </summary>
        internal static string LogConfigurationStoreNotFound {
            get {
                return ResourceManager.GetString("LogConfigurationStoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process plugin assembly {0} with the following exception(s):.
        /// </summary>
        internal static string LogFailedToProcessPluginAssembly {
            get {
                return ResourceManager.GetString("LogFailedToProcessPluginAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unmanaged DLL: {0}.
        /// </summary>
        internal static string LogFoundUnmanagedDLL {
            get {
                return ResourceManager.GetString("LogFoundUnmanagedDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License provider not found - defaulting to local license provider..
        /// </summary>
        internal static string LogLicenseProviderNotFound {
            get {
                return ResourceManager.GetString("LogLicenseProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local configuration store not found - defaulting to LocalFileSettingsProvider.
        /// </summary>
        internal static string LogLocalConfigurationStoreNotFound {
            get {
                return ResourceManager.GetString("LogLocalConfigurationStoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin: {0}.
        /// </summary>
        internal static string LogPluginLoaded {
            get {
                return ResourceManager.GetString("LogPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time provider not found - defaulting to local machine time..
        /// </summary>
        internal static string LogTimeProviderNotFound {
            get {
                return ResourceManager.GetString("LogTimeProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string MenuAlertViewer {
            get {
                return ResourceManager.GetString("MenuAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuCloseWindow {
            get {
                return ResourceManager.GetString("MenuCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workspace.
        /// </summary>
        internal static string MenuCloseWorkspace {
            get {
                return ResourceManager.GetString("MenuCloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Editor.
        /// </summary>
        internal static string MenuConfigureSettings {
            get {
                return ResourceManager.GetString("MenuConfigureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string MenuContents {
            get {
                return ResourceManager.GetString("MenuContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string MenuIndex {
            get {
                return ResourceManager.GetString("MenuIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Group After.
        /// </summary>
        internal static string MenuInsertGroupAfter {
            get {
                return ResourceManager.GetString("MenuInsertGroupAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string MenuInsertGroupAsChild {
            get {
                return ResourceManager.GetString("MenuInsertGroupAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Group Before.
        /// </summary>
        internal static string MenuInsertGroupBefore {
            get {
                return ResourceManager.GetString("MenuInsertGroupBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Separator After.
        /// </summary>
        internal static string MenuInsertSeparatorAfter {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Separator.
        /// </summary>
        internal static string MenuInsertSeparatorAsChild {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Separator Before.
        /// </summary>
        internal static string MenuInsertSeparatorBefore {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string MenuUtilities {
            get {
                return ResourceManager.GetString("MenuUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extension point cannot extend IExtensionPoint..
        /// </summary>
        internal static string MessageCannotExtendIExtensionPoint {
            get {
                return ResourceManager.GetString("MessageCannotExtendIExtensionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background task is still running.  Are you sure you want to cancel?.
        /// </summary>
        internal static string MessageConfirmCancelTask {
            get {
                return ResourceManager.GetString("MessageConfirmCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been modified and changes will be lost.  Discard changes and close?.
        /// </summary>
        internal static string MessageConfirmDiscardChangesBeforeClosing {
            get {
                return ResourceManager.GetString("MessageConfirmDiscardChangesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings meta-data defined in locally installed plugins?.
        /// </summary>
        internal static string MessageConfirmImportSettingsMetaData {
            get {
                return ResourceManager.GetString("MessageConfirmImportSettingsMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must restart in order to apply the new display language. Would you like to restart now?.
        /// </summary>
        internal static string MessageDisplayLanguageChangedRestartRequired {
            get {
                return ResourceManager.GetString("MessageDisplayLanguageChangedRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding plugins....
        /// </summary>
        internal static string MessageFindingPlugins {
            get {
                return ResourceManager.GetString("MessageFindingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration pages exist..
        /// </summary>
        internal static string MessageNoConfigurationPagesExist {
            get {
                return ResourceManager.GetString("MessageNoConfigurationPagesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group contains one or more items. Items may not be deleted, but can be hidden..
        /// </summary>
        internal static string MessageNodeNotEmpty {
            get {
                return ResourceManager.GetString("MessageNodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this setting back to its default value?.
        /// </summary>
        internal static string MessageReset {
            get {
                return ResourceManager.GetString("MessageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings back to default values?.
        /// </summary>
        internal static string MessageResetAll {
            get {
                return ResourceManager.GetString("MessageResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been modified.  Save changes?.
        /// </summary>
        internal static string MessageSaveModified {
            get {
                return ResourceManager.GetString("MessageSaveModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the selected settings values.  Please ensure the values entered are properly formatted for the data type..
        /// </summary>
        internal static string MessageSaveSettingFailed {
            get {
                return ResourceManager.GetString("MessageSaveSettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings scope not defined..
        /// </summary>
        internal static string MessageSettingsScopeNotDefined {
            get {
                return ResourceManager.GetString("MessageSettingsScopeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings store is currently offline.  Please try again later..
        /// </summary>
        internal static string MessageSettingsStoreOffline {
            get {
                return ResourceManager.GetString("MessageSettingsStoreOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred which prevents the further use of this application. This application will now shut down to prevent damage to the system..
        /// </summary>
        internal static string MessageUnexpectedErrorQuit {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized format.
        /// </summary>
        internal static string MessageUnrecognizedFormat {
            get {
                return ResourceManager.GetString("MessageUnrecognizedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating your personal preferences ....
        /// </summary>
        internal static string MessageUpdatingPreferences {
            get {
                return ResourceManager.GetString("MessageUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors have occurred while updating your preferences.  Some of your preferences may not have been properly configured..
        /// </summary>
        internal static string MessageUserUpgradeFailures {
            get {
                return ResourceManager.GetString("MessageUserUpgradeFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value required.
        /// </summary>
        internal static string MessageValueRequired {
            get {
                return ResourceManager.GetString("MessageValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has failed to start.  Please check the log for more details..
        /// </summary>
        internal static string ShredFailedToStart {
            get {
                return ResourceManager.GetString("ShredFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has failed to stop.  Please check the log for more details..
        /// </summary>
        internal static string ShredFailedToStop {
            get {
                return ResourceManager.GetString("ShredFailedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has started successfully..
        /// </summary>
        internal static string ShredStartedSuccessfully {
            get {
                return ResourceManager.GetString("ShredStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} Shred.
        /// </summary>
        internal static string ShredStarting {
            get {
                return ResourceManager.GetString("ShredStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has stopped successfully..
        /// </summary>
        internal static string ShredStoppedSuccessfully {
            get {
                return ResourceManager.GetString("ShredStoppedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0} Shred.
        /// </summary>
        internal static string ShredStopping {
            get {
                return ResourceManager.GetString("ShredStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string TitleAlertViewer {
            get {
                return ResourceManager.GetString("TitleAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TitleCancel {
            get {
                return ResourceManager.GetString("TitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TitleClose {
            get {
                return ResourceManager.GetString("TitleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Assistant.
        /// </summary>
        internal static string TitleCloseAssistant {
            get {
                return ResourceManager.GetString("TitleCloseAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string TitleDateFormat {
            get {
                return ResourceManager.GetString("TitleDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string TitleDefaultValue {
            get {
                return ResourceManager.GetString("TitleDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Value.
        /// </summary>
        internal static string TitleEditValue {
            get {
                return ResourceManager.GetString("TitleEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string TitleGroup {
            get {
                return ResourceManager.GetString("TitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string TitleMenuOptions {
            get {
                return ResourceManager.GetString("TitleMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string TitleNext {
            get {
                return ResourceManager.GetString("TitleNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string TitlePrevious {
            get {
                return ResourceManager.GetString("TitlePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string TitleProperty {
            get {
                return ResourceManager.GetString("TitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string TitleRename {
            get {
                return ResourceManager.GetString("TitleRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string TitleScope {
            get {
                return ResourceManager.GetString("TitleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Editor.
        /// </summary>
        internal static string TitleSettingsEditor {
            get {
                return ResourceManager.GetString("TitleSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string TitleToolbar {
            get {
                return ResourceManager.GetString("TitleToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TitleType {
            get {
                return ResourceManager.GetString("TitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Preferences ....
        /// </summary>
        internal static string TitleUpdatingPreferences {
            get {
                return ResourceManager.GetString("TitleUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string TitleValue {
            get {
                return ResourceManager.GetString("TitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string TitleVersion {
            get {
                return ResourceManager.GetString("TitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string ToolbarAddGroup {
            get {
                return ResourceManager.GetString("ToolbarAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Separator.
        /// </summary>
        internal static string ToolbarAddSeparator {
            get {
                return ResourceManager.GetString("ToolbarAddSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ToolbarRemove {
            get {
                return ResourceManager.GetString("ToolbarRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string ToolbarRename {
            get {
                return ResourceManager.GetString("ToolbarRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can configure this item, but you do not have permission to use it..
        /// </summary>
        internal static string TooltipActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:
        ///You can configure this item, but you do not have permission to use it..
        /// </summary>
        internal static string TooltipFormatActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipFormatActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings meta-data from local plugins.
        /// </summary>
        internal static string TooltipImportSettingsMetaData {
            get {
                return ResourceManager.GetString("TooltipImportSettingsMetaData", resourceCulture);
            }
        }
    }
}
