/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Common.ElectronicBill.VNPTBachMai {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VNPTBachMai.PublishServiceSoap")]
    public interface PublishServiceSoap {
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse ImportAndPublishInv(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse> ImportAndPublishInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvPattern", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse ImportInvPattern(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvPattern", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse> ImportInvPatternAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse ImportInv(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse> ImportInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest request);
        
        // CODEGEN: Generating message contract since element name invIDs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse publishInv(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse> publishInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest request);
        
        // CODEGEN: Generating message contract since element name XMLCusData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse UpdateCus(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse> UpdateCusAsync(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest request);
        
        // CODEGEN: Generating message contract since element name certSerial from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse setCusCert(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse> setCusCertAsync(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvByPatternSerial", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse ImportInvByPatternSerial(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvByPatternSerial", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse> ImportInvByPatternSerialAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest request);
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvFkey", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse publishInvFkey(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvFkey", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse> publishInvFkeyAsync(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest request);
        
        // CODEGEN: Generating message contract since element name lsFkey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteInvFkey", ReplyAction="*")]
        Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse deleteInvFkey(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteInvFkey", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse> deleteInvFkeyAsync(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInv", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequestBody Body;
        
        public ImportAndPublishInvRequest() {
        }
        
        public ImportAndPublishInvRequest(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int convert;
        
        public ImportAndPublishInvRequestBody() {
        }
        
        public ImportAndPublishInvRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponseBody Body;
        
        public ImportAndPublishInvResponse() {
        }
        
        public ImportAndPublishInvResponse(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportAndPublishInvResult;
        
        public ImportAndPublishInvResponseBody() {
        }
        
        public ImportAndPublishInvResponseBody(string ImportAndPublishInvResult) {
            this.ImportAndPublishInvResult = ImportAndPublishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPattern", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequestBody Body;
        
        public ImportInvPatternRequest() {
        }
        
        public ImportInvPatternRequest(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string serial;
        
        public ImportInvPatternRequestBody() {
        }
        
        public ImportInvPatternRequestBody(string xmlInvData, string username, string password, int convert, string pattern, string serial) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPatternResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponseBody Body;
        
        public ImportInvPatternResponse() {
        }
        
        public ImportInvPatternResponse(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvPatternResult;
        
        public ImportInvPatternResponseBody() {
        }
        
        public ImportInvPatternResponseBody(string ImportInvPatternResult) {
            this.ImportInvPatternResult = ImportInvPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInv", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequestBody Body;
        
        public ImportInvRequest() {
        }
        
        public ImportInvRequest(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        public ImportInvRequestBody() {
        }
        
        public ImportInvRequestBody(string xmlInvData, string username, string password, int convert) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponseBody Body;
        
        public ImportInvResponse() {
        }
        
        public ImportInvResponse(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvResult;
        
        public ImportInvResponseBody() {
        }
        
        public ImportInvResponseBody(string ImportInvResult) {
            this.ImportInvResult = ImportInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInv", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequestBody Body;
        
        public publishInvRequest() {
        }
        
        public publishInvRequest(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ArrayOfInt invIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvRequestBody() {
        }
        
        public publishInvRequestBody(Inventec.Common.ElectronicBill.VNPTBachMai.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            this.invIDs = invIDs;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponseBody Body;
        
        public publishInvResponse() {
        }
        
        public publishInvResponse(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvResult;
        
        public publishInvResponseBody() {
        }
        
        public publishInvResponseBody(string publishInvResult) {
            this.publishInvResult = publishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCus", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequestBody Body;
        
        public UpdateCusRequest() {
        }
        
        public UpdateCusRequest(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLCusData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> convert;
        
        public UpdateCusRequestBody() {
        }
        
        public UpdateCusRequestBody(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            this.XMLCusData = XMLCusData;
            this.username = username;
            this.pass = pass;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponseBody Body;
        
        public UpdateCusResponse() {
        }
        
        public UpdateCusResponse(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCusResult;
        
        public UpdateCusResponseBody() {
        }
        
        public UpdateCusResponseBody(int UpdateCusResult) {
            this.UpdateCusResult = UpdateCusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCert", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequestBody Body;
        
        public setCusCertRequest() {
        }
        
        public setCusCertRequest(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string certSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string certString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public setCusCertRequestBody() {
        }
        
        public setCusCertRequestBody(string certSerial, string certString, string cusCode, string username, string pass) {
            this.certSerial = certSerial;
            this.certString = certString;
            this.cusCode = cusCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponseBody Body;
        
        public setCusCertResponse() {
        }
        
        public setCusCertResponse(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setCusCertResult;
        
        public setCusCertResponseBody() {
        }
        
        public setCusCertResponseBody(int setCusCertResult) {
            this.setCusCertResult = setCusCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerial", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequestBody Body;
        
        public ImportInvByPatternSerialRequest() {
        }
        
        public ImportInvByPatternSerialRequest(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int convert;
        
        public ImportInvByPatternSerialRequestBody() {
        }
        
        public ImportInvByPatternSerialRequestBody(string xmlInvData, string username, string pass, string pattern, string serial, int convert) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerialResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponseBody Body;
        
        public ImportInvByPatternSerialResponse() {
        }
        
        public ImportInvByPatternSerialResponse(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvByPatternSerialResult;
        
        public ImportInvByPatternSerialResponseBody() {
        }
        
        public ImportInvByPatternSerialResponseBody(string ImportInvByPatternSerialResult) {
            this.ImportInvByPatternSerialResult = ImportInvByPatternSerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequestBody Body;
        
        public publishInvFkeyRequest() {
        }
        
        public publishInvFkeyRequest(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public publishInvFkeyRequestBody() {
        }
        
        public publishInvFkeyRequestBody(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.lsFkey = lsFkey;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponseBody Body;
        
        public publishInvFkeyResponse() {
        }
        
        public publishInvFkeyResponse(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvFkeyResult;
        
        public publishInvFkeyResponseBody() {
        }
        
        public publishInvFkeyResponseBody(string publishInvFkeyResult) {
            this.publishInvFkeyResult = publishInvFkeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequestBody Body;
        
        public deleteInvFkeyRequest() {
        }
        
        public deleteInvFkeyRequest(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        public deleteInvFkeyRequestBody() {
        }
        
        public deleteInvFkeyRequestBody(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern) {
            this.lsFkey = lsFkey;
            this.Account = Account;
            this.ACpass = ACpass;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponseBody Body;
        
        public deleteInvFkeyResponse() {
        }
        
        public deleteInvFkeyResponse(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteInvFkeyResult;
        
        public deleteInvFkeyResponseBody() {
        }
        
        public deleteInvFkeyResponseBody(string deleteInvFkeyResult) {
            this.deleteInvFkeyResult = deleteInvFkeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublishServiceSoapChannel : Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap>, Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap {
        
        public PublishServiceSoapClient() {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportAndPublishInv(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest request) {
            return base.Channel.ImportAndPublishInv(request);
        }
        
        public string ImportAndPublishInv(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportAndPublishInv(inValue);
            return retVal.Body.ImportAndPublishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportAndPublishInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest request) {
            return base.Channel.ImportAndPublishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvResponse> ImportAndPublishInvAsync(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportAndPublishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInvPattern(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest request) {
            return base.Channel.ImportInvPattern(request);
        }
        
        public string ImportInvPattern(string xmlInvData, string username, string password, int convert, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInvPattern(inValue);
            return retVal.Body.ImportInvPatternResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInvPatternAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest request) {
            return base.Channel.ImportInvPatternAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternResponse> ImportInvPatternAsync(string xmlInvData, string username, string password, int convert, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvPatternRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInvPatternAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInv(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest request) {
            return base.Channel.ImportInv(request);
        }
        
        public string ImportInv(string xmlInvData, string username, string password, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInv(inValue);
            return retVal.Body.ImportInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest request) {
            return base.Channel.ImportInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvResponse> ImportInvAsync(string xmlInvData, string username, string password, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.publishInv(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest request) {
            return base.Channel.publishInv(request);
        }
        
        public string publishInv(Inventec.Common.ElectronicBill.VNPTBachMai.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).publishInv(inValue);
            return retVal.Body.publishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.publishInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest request) {
            return base.Channel.publishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvResponse> publishInvAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).publishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.UpdateCus(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest request) {
            return base.Channel.UpdateCus(request);
        }
        
        public int UpdateCus(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).UpdateCus(inValue);
            return retVal.Body.UpdateCusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.UpdateCusAsync(Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest request) {
            return base.Channel.UpdateCusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusResponse> UpdateCusAsync(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).UpdateCusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.setCusCert(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest request) {
            return base.Channel.setCusCert(request);
        }
        
        public int setCusCert(string certSerial, string certString, string cusCode, string username, string pass) {
            Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).setCusCert(inValue);
            return retVal.Body.setCusCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.setCusCertAsync(Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest request) {
            return base.Channel.setCusCertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertResponse> setCusCertAsync(string certSerial, string certString, string cusCode, string username, string pass) {
            Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).setCusCertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInvByPatternSerial(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest request) {
            return base.Channel.ImportInvByPatternSerial(request);
        }
        
        public string ImportInvByPatternSerial(string xmlInvData, string username, string pass, string pattern, string serial, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInvByPatternSerial(inValue);
            return retVal.Body.ImportInvByPatternSerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.ImportInvByPatternSerialAsync(Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest request) {
            return base.Channel.ImportInvByPatternSerialAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialResponse> ImportInvByPatternSerialAsync(string xmlInvData, string username, string pass, string pattern, string serial, int convert) {
            Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.ImportInvByPatternSerialRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).ImportInvByPatternSerialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.publishInvFkey(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest request) {
            return base.Channel.publishInvFkey(request);
        }
        
        public string publishInvFkey(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).publishInvFkey(inValue);
            return retVal.Body.publishInvFkeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.publishInvFkeyAsync(Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest request) {
            return base.Channel.publishInvFkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyResponse> publishInvFkeyAsync(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial) {
            Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.publishInvFkeyRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).publishInvFkeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.deleteInvFkey(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest request) {
            return base.Channel.deleteInvFkey(request);
        }
        
        public string deleteInvFkey(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern) {
            Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequestBody();
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse retVal = ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).deleteInvFkey(inValue);
            return retVal.Body.deleteInvFkeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse> Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap.deleteInvFkeyAsync(Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest request) {
            return base.Channel.deleteInvFkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyResponse> deleteInvFkeyAsync(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern) {
            Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest inValue = new Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequest();
            inValue.Body = new Inventec.Common.ElectronicBill.VNPTBachMai.deleteInvFkeyRequestBody();
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            return ((Inventec.Common.ElectronicBill.VNPTBachMai.PublishServiceSoap)(this)).deleteInvFkeyAsync(inValue);
        }
    }
}
