/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Desktop.Common.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Desktop.Common.LibraryMessage.MessageViResource", typeof(MessageViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng không được hỗ trợ ở phiên bản hiện tại, vui lòng thử lại sau.
        /// </summary>
        internal static string ChucNangDangPhatTrienVuiLongThuLaiSau {
            get {
                return ResourceManager.GetString("ChucNangDangPhatTrienVuiLongThuLaiSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đính kèm dung lượng quá lớn.
        /// </summary>
        internal static string DungLuongFileDinhKemQuaLon {
            get {
                return ResourceManager.GetString("DungLuongFileDinhKemQuaLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền không hợp lệ.
        /// </summary>
        internal static string HeThongTBBanQuyenKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBBanQuyenKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy lưu lại dữ liệu trước khi kết thúc.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn bỏ duyệt khóa khóa?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn bỏ khóa dữ liệu?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn duyệt khóa?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn gửi lại yêu cầu.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn hủy dữ liệu?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn khóa dữ liệu?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa dữ liệu?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nhập vào thiếu trường dữ liệu bắt buộc.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nhập vào thiếu trường dữ liệu bắt buộc.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe1 {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối đến máy chủ không ổn định.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongOnDinh {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongOnDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối tới máy chủ không tốt.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối tới máy chủ không ổn định.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuNotStability {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuNotStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối tới máy chủ thất bại.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối tới máy chủ tốt.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thành công.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThanhCong {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thất bại.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc bị hết hiệu lực, có thể do bạn đã ngừng sử dụng phần mềm trong một khoảng thời gian dài hoặc kết nối đến hệ thống máy chủ bị gián đoạn tạm thời. Phần mềm sẽ tự động đăng xuất. Vui lòng đăng nhập lại để tiếp tục sử dụng..
        /// </summary>
        internal static string HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai {
            get {
                return ResourceManager.GetString("HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu bắt buộc phải nhập.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu bắt buộc phải nhập.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap1 {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thất bại. Vui lòng liên hệ với quản trị hệ thống để được hỗ trợ.
        /// </summary>
        internal static string HeThongTBXuatHienExceptionChuaKiemDuocSoat {
            get {
                return ResourceManager.GetString("HeThongTBXuatHienExceptionChuaKiemDuocSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tiếp đón bệnh nhân thành công, tuy nhiên thông tin trả về không hợp lệ..
        /// </summary>
        internal static string HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang kiểm tra phiên bản cập nhật ....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoUpdatingDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoUpdatingDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý, vui lòng đợi....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đến bé hơn thời gian từ.
        /// </summary>
        internal static string HeThongThongBaoThoiGianDenBeHonThoiGianTu {
            get {
                return ResourceManager.GetString("HeThongThongBaoThoiGianDenBeHonThoiGianTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%....
        /// </summary>
        internal static string HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong {
            get {
                return ResourceManager.GetString("HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đợi.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu.
        /// </summary>
        internal static string NguoiDungChuaNhapMatKhauDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapMatKhauDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tài khoản.
        /// </summary>
        internal static string NguoiDungChuaNhapTaiKhoanDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapTaiKhoanDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không chính xác.
        /// </summary>
        internal static string NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac {
            get {
                return ResourceManager.GetString("NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        internal static string NguoiDungNhapDuLieuKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapDuLieuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm  không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapNamKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapNamSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày  không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapNgayKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian phải lớn hơn ngày hiện tại.
        /// </summary>
        internal static string NguoiDungNhapNgayPhaiNhoHonNgayHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayPhaiNhoHonNgayHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tuổi phải nhỏ hơn ngày hiện tại.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa được cấu hình vào phòng làm việc nào, vui lòng liên hệ quản trị hệ thống để được hỗ trợ..
        /// </summary>
        internal static string NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng được cấu hình làm việc ở phòng nhưng không được gán quyền vào phòng đó, vui lòng chọn phòng khác hoặc kiểm tra lại cấu hình phần mềm..
        /// </summary>
        internal static string NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHinh {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHin" +
                        "h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không được gán quyền vào phòng làm việc, vui lòng liên hệ với quản trị hệ thống để được hỗ trợ.
        /// </summary>
        internal static string NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu bắt đầu sổ thu chi phải là số nguyên có giá trị trong khoảng từ 1 đến 1.000.000.000.
        /// </summary>
        internal static string NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu phải là số nguyên có giá trị trong khoảng từ 0 đến 1.000.000.000.
        /// </summary>
        internal static string NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng  không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapThangKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng sinh không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapThangSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng tuổi phải nhỏ hơn ngày hiện tại.
        /// </summary>
        internal static string NguoiDungNhapThangSinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi không hợp lệ, vui lòng nhập lại.
        /// </summary>
        internal static string NguoiDungNhapTuoiBenhNhanKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapTuoiBenhNhanKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần mềm không kết nối được tới máy chủ hệ thống. Vui lòng kiểm tra lại cấu hình và kết nối.
        /// </summary>
        internal static string PhanMemKhongKetNoiDuocToiMayChuHeThong {
            get {
                return ResourceManager.GetString("PhanMemKhongKetNoiDuocToiMayChuHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập số lượng.
        /// </summary>
        internal static string SuaChiDinhDichVu_KhongCoDoiSoLuong {
            get {
                return ResourceManager.GetString("SuaChiDinhDichVu_KhongCoDoiSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không có quyền thực hiện chức năng.
        /// </summary>
        internal static string TaiKhoanKhongCoQuyenThucHienChucNang {
            get {
                return ResourceManager.GetString("TaiKhoanKhongCoQuyenThucHienChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu trường dữ liệu bắt buộc.
        /// </summary>
        internal static string ThieuTruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("ThieuTruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có kết quả.
        /// </summary>
        internal static string ThongBaoDuLieuTrong {
            get {
                return ResourceManager.GetString("ThongBaoDuLieuTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu bệnh nhân khi quẹt thẻ qua đầu đọc npc, mã thẻ {0}.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo kết quả tìm kiếm bệnh nhân.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaCanhBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaLoi {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaThongBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string TieuDeThongTinHienThiPhanTrang {
            get {
                return ResourceManager.GetString("TieuDeThongTinHienThiPhanTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu bắt buộc.
        /// </summary>
        internal static string TruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("TruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ điều trị đã kết thúc.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là người tạo ra yêu cầu này.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng hiện tại không phải là phòng chỉ định dịch vụ.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn thuốc, vật tư để trả.
        /// </summary>
        internal static string XuatTraThuoc_ChuaChonThuocVatTuDeTra {
            get {
                return ResourceManager.GetString("XuatTraThuoc_ChuaChonThuocVatTuDeTra", resourceCulture);
            }
        }
    }
}
