/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Desktop.Common.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageMyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageMyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Desktop.Common.LibraryMessage.MessageMyResource", typeof(MessageMyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လုပ်ဆောင်ချက်ကို လက်ရှိဗားရှင်းတွင် မပံ့ပိုးပါ၊ ကျေးဇူးပြု၍ နောက်မှ ထပ်ကြိုးစားပါ။.
        /// </summary>
        internal static string ChucNangDangPhatTrienVuiLongThuLaiSau {
            get {
                return ResourceManager.GetString("ChucNangDangPhatTrienVuiLongThuLaiSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပူးတွဲပါဖိုင်အရွယ်အစား ကြီးလွန်းသည်။.
        /// </summary>
        internal static string DungLuongFileDinhKemQuaLon {
            get {
                return ResourceManager.GetString("DungLuongFileDinhKemQuaLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မူပိုင်ခွင့် မမှန်ကန်ပါ။.
        /// </summary>
        internal static string HeThongTBBanQuyenKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBBanQuyenKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မပြီးဆုံးမီ ဒေတာကို သိမ်းဆည်းပါ။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သော့ခတ်သော့ကို ပြန်လှန်ကြည့်လိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဒေတာကို ပြန်ဖွင့်လိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သော့ကိုရှာဖွေလိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to တောင်းဆိုချက်ကို ပြန်လည်ပေးပို့လိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဒေတာကို ဖျက်လိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဒေတာကို လော့ခ်ချလိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဒေတာကို ဖျက်လိုသည်မှာ သေချာပါသလား။.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထည့်သွင်းဒေတာသည် လိုအပ်သောအကွက်များ ပျောက်ဆုံးနေပါသည်။.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထည့်သွင်းဒေတာသည် လိုအပ်သောအကွက်များ ပျောက်ဆုံးနေပါသည်။.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe1 {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆာဗာသို့ ချိတ်ဆက်မှုသည် မတည်ငြိမ်ပါ။.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongOnDinh {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongOnDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆာဗာသို့ ချိတ်ဆက်မှု မကောင်းပါ။.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆာဗာသို့ ချိတ်ဆက်မှုသည် မတည်ငြိမ်ပါ။.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuNotStability {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuNotStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆာဗာသို့ ချိတ်ဆက်မှု မအောင်မြင်ပါ။.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆာဗာချိတ်ဆက်မှုကောင်းသည်။.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အောင်မြင်စွာကိုင်တွယ်ပါ။.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThanhCong {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကိုင်တွယ်မှု မအောင်မြင်.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သင်သည် ဆော့ဖ်ဝဲလ်ကို အချိန်အတော်ကြာ ရပ်တန့်ထားသောကြောင့် သို့မဟုတ် ဆာဗာစနစ်သို့ ချိတ်ဆက်မှု ခေတ္တပြတ်တောက်သွားသောကြောင့် ဆက်ရှင်အား ပျက်ပြယ်သွားခြင်း ဖြစ်နိုင်ပါသည်။ ဆော့ဖ်ဝဲလ်သည် အလိုအလျောက် ထွက်ပါမည်။ ဆက်လက်အသုံးပြုရန် ကျေးဇူးပြု၍ ထပ်မံဝင်ရောက်ပါ။.
        /// </summary>
        internal static string HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai {
            get {
                return ResourceManager.GetString("HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဝင်ရန် လိုအပ်သော အကွက်.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဝင်ရန် လိုအပ်သော အကွက်.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap1 {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကိုင်တွယ်မှု မအောင်မြင်။ အကူအညီအတွက် ကျေးဇူးပြု၍ သင့်စနစ်စီမံခန့်ခွဲသူကို ဆက်သွယ်ပါ။.
        /// </summary>
        internal static string HeThongTBXuatHienExceptionChuaKiemDuocSoat {
            get {
                return ResourceManager.GetString("HeThongTBXuatHienExceptionChuaKiemDuocSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လူနာမှတ်ပုံတင်ခြင်း အောင်မြင်သော်လည်း ပြန်ပေးထားသော အချက်အလက်သည် မမှန်ကန်ပါ။.
        /// </summary>
        internal static string HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စနစ်သည် အပ်ဒိတ်ဗားရှင်းအတွက် စစ်ဆေးနေသည်....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoUpdatingDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoUpdatingDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လုပ်ဆောင်နေသည်၊ ခဏစောင့်ပါ....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆိုက်ရောက်ချိန်က အချိန်ထက်နည်းတယ်။.
        /// </summary>
        internal static string HeThongThongBaoThoiGianDenBeHonThoiGianTu {
            get {
                return ResourceManager.GetString("HeThongThongBaoThoiGianDenBeHonThoiGianTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%....
        /// </summary>
        internal static string HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong {
            get {
                return ResourceManager.GetString("HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကြောင်းကြားပါ။.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကျေးဇူးပြုပြီးခဏစောင့်ပါ.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သင့်စကားဝှက်ကို သင်မထည့်ရသေးပါ။.
        /// </summary>
        internal static string NguoiDungChuaNhapMatKhauDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapMatKhauDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သင်သည် စာရင်းမသွင်းရသေးပါ။.
        /// </summary>
        internal static string NguoiDungChuaNhapTaiKhoanDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapTaiKhoanDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အတည်ပြုချက် စကားဝှက် မမှန်ပါ။.
        /// </summary>
        internal static string NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac {
            get {
                return ResourceManager.GetString("NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မမှန်ကန်သောဒေတာ.
        /// </summary>
        internal static string NguoiDungNhapDuLieuKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapDuLieuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မမှန်ကန်သောနှစ်၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNamKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မွေးသက္ကရာဇ် မမှန်ကန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNamSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရက်စွဲမမှန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNgayKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အချိန်သည် လက်ရှိရက်စွဲထက် ပိုနေရပါမည်။.
        /// </summary>
        internal static string NguoiDungNhapNgayPhaiNhoHonNgayHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayPhaiNhoHonNgayHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မွေးသက္ကရာဇ် မမှန်ကန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသက်ရက်စွဲသည် လက်ရှိရက်စွဲထက် နည်းနေရပါမည်။.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သင့်အကောင့်ကို မည်သည့်ရုံးတွင်မဆို ပြင်ဆင်သတ်မှတ်ထားခြင်းမရှိပါ၊ အကူအညီအတွက် သင့်စနစ်စီမံခန့်ခွဲသူကို ဆက်သွယ်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသုံးပြုသူသည် အခန်းတွင်းတွင် အလုပ်လုပ်ရန် စီစဉ်သတ်မှတ်ထားသော်လည်း ထိုအခန်းသို့ ဝင်ရောက်ရန် ခွင့်မပြုပါ၊ ကျေးဇူးပြု၍ အခြားအခန်းကို ရွေးပါ သို့မဟုတ် ဆော့ဖ်ဝဲဖွဲ့စည်းပုံကို ထပ်မံစစ်ဆေးပါ။.
        /// </summary>
        internal static string NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHinh {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHin" +
                        "h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသုံးပြုသူသည် ရုံးခန်းအတွင်းသို့ ဝင်ရောက်ရန် အခွင့်မရှိပါ၊ ပံ့ပိုးကူညီမှုအတွက် စနစ်စီမံခန့်ခွဲသူကို ဆက်သွယ်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဝင်ငွေနှင့် အသုံးစရိတ်စာအုပ်အစရှိ ဘောက်ချာအရေအတွက်သည် 1 နှင့် 1,000,000,000 VND အကြား တန်ဖိုးရှိသော ကိန်းပြည့်ဖြစ်ရပါမည်။.
        /// </summary>
        internal static string NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆန္ဒမဲအရေအတွက်သည် 0 နှင့် 1,000,000,000 ကြားတန်ဖိုးရှိသော ကိန်းပြည့်ဖြစ်ရပါမည်။.
        /// </summary>
        internal static string NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကောင့် သို့မဟုတ် စကားဝှက် မမှန်ကန်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လမမှန်ကန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapThangKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မွေးလ မမှန်ကန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapThangSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လ၏အသက်သည် လက်ရှိရက်စွဲထက် နည်းနေရမည်။.
        /// </summary>
        internal static string NguoiDungNhapThangSinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသက်မမှန်ကန်ပါ၊ ကျေးဇူးပြု၍ ပြန်ထည့်ပါ။.
        /// </summary>
        internal static string NguoiDungNhapTuoiBenhNhanKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapTuoiBenhNhanKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆော့ဖ်ဝဲသည် စနစ်ဆာဗာသို့ ချိတ်ဆက်၍မရပါ။ ဖွဲ့စည်းမှုပုံစံနှင့် ချိတ်ဆက်မှုကို ထပ်မံစစ်ဆေးပါ။.
        /// </summary>
        internal static string PhanMemKhongKetNoiDuocToiMayChuHeThong {
            get {
                return ResourceManager.GetString("PhanMemKhongKetNoiDuocToiMayChuHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပမာဏ မထည့်ဘူး။.
        /// </summary>
        internal static string SuaChiDinhDichVu_KhongCoDoiSoLuong {
            get {
                return ResourceManager.GetString("SuaChiDinhDichVu_KhongCoDoiSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကောင့်သည် လုပ်ဆောင်ချက်ကို လုပ်ဆောင်ရန် ခွင့်ပြုချက် မရှိပါ။.
        /// </summary>
        internal static string TaiKhoanKhongCoQuyenThucHienChucNang {
            get {
                return ResourceManager.GetString("TaiKhoanKhongCoQuyenThucHienChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လိုအပ်သောအကွက်များ ပျောက်ဆုံးနေပါသည်။.
        /// </summary>
        internal static string ThieuTruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("ThieuTruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရလဒ်မရှိပါ။.
        /// </summary>
        internal static string ThongBaoDuLieuTrong {
            get {
                return ResourceManager.GetString("ThongBaoDuLieuTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to npc reader မှ ကတ်ကို ပွတ်ဆွဲသောအခါ လူနာဒေတာ၊ တဂ်ကုဒ် {0}.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လူနာရှာဖွေမှုရလဒ်များကိုကြေငြာခြင်း။.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတိပေးချက်.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaCanhBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အမှား.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaLoi {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကြောင်းကြားပါ။.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaThongBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စာမျက်နှာ.
        /// </summary>
        internal static string TieuDeThongTinHienThiPhanTrang {
            get {
                return ResourceManager.GetString("TieuDeThongTinHienThiPhanTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လိုအပ်သောအကွက်.
        /// </summary>
        internal static string TruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("TruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကုသမှုမှတ်တမ်း ပြီးသွားပါပြီ။.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သင်သည် ဤတောင်းဆိုချက်ကို ဖန်တီးသူမဟုတ်ပါ။.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ရှိအခန်းသည် သတ်မှတ်ထားသော အခန်းမဟုတ်ပါ။.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပေးဆောင်ရန် ဆေးဝါးနှင့် ထောက်ပံ့ရေးပစ္စည်းများကို မရွေးချယ်ခဲ့ပါ။.
        /// </summary>
        internal static string XuatTraThuoc_ChuaChonThuocVatTuDeTra {
            get {
                return ResourceManager.GetString("XuatTraThuoc_ChuaChonThuocVatTuDeTra", resourceCulture);
            }
        }
    }
}
