/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Desktop.Common.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageEnResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageEnResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.Desktop.Common.LibraryMessage.MessageEnResource", typeof(MessageEnResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function is not supported in the current version, please try again later.
        /// </summary>
        internal static string ChucNangDangPhatTrienVuiLongThuLaiSau {
            get {
                return ResourceManager.GetString("ChucNangDangPhatTrienVuiLongThuLaiSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments too large.
        /// </summary>
        internal static string DungLuongFileDinhKemQuaLon {
            get {
                return ResourceManager.GetString("DungLuongFileDinhKemQuaLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright invalid.
        /// </summary>
        internal static string HeThongTBBanQuyenKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBBanQuyenKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save data before the end.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanChuaLuuLaiDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to remove browse lock?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the lock data?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonBoKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to browse the lock?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonDuyetKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to resubmit request.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonGuiLaiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sure you want to cancel the data?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonHuyDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to lock the data?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonKhoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sure you want to delete the data?.
        /// </summary>
        internal static string HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong {
            get {
                return ResourceManager.GetString("HeThongTBCuaSoThongBaoBanCoMuonXoaDuLieuKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data entered data fields required.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data entered data fields required.
        /// </summary>
        internal static string HeThongTBDuLieuNhapVaoKhongHopLe1 {
            get {
                return ResourceManager.GetString("HeThongTBDuLieuNhapVaoKhongHopLe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the server unstable.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongOnDinh {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongOnDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the server is not good.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuKhongTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuKhongTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the server unstable.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuNotStability {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuNotStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server failure.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good connection to the server.
        /// </summary>
        internal static string HeThongTBKetNoiDenMayChuTot {
            get {
                return ResourceManager.GetString("HeThongTBKetNoiDenMayChuTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Success.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThanhCong {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling failure.
        /// </summary>
        internal static string HeThongTBKQXLYCCuaFrontendThatBai {
            get {
                return ResourceManager.GetString("HeThongTBKQXLYCCuaFrontendThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired, probably because you have stopped using the software for a long time or connect to the host system is temporarily interrupted. The software will automatically log out. Please sign in again to continue using..
        /// </summary>
        internal static string HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai {
            get {
                return ResourceManager.GetString("HeThongTBNguoiDungDaHetPhienLamViecVuiLongDangNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fields required to enter.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fields required to enter.
        /// </summary>
        internal static string HeThongTBTruongDuLieuBatBuocPhaiNhap1 {
            get {
                return ResourceManager.GetString("HeThongTBTruongDuLieuBatBuocPhaiNhap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling failure. Please contact your system administrator for assistance.
        /// </summary>
        internal static string HeThongTBXuatHienExceptionChuaKiemDuocSoat {
            get {
                return ResourceManager.GetString("HeThongTBXuatHienExceptionChuaKiemDuocSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful reception of patients, but the information returned is not valid..
        /// </summary>
        internal static string HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe {
            get {
                return ResourceManager.GetString("HeThongThongBaoKetQuaTraVeCuaBackendKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is checking the updated version ....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoUpdatingDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoUpdatingDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing, please wait ....
        /// </summary>
        internal static string HeThongThongBaoMoTaChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoMoTaChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to be less than the time from.
        /// </summary>
        internal static string HeThongThongBaoThoiGianDenBeHonThoiGianTu {
            get {
                return ResourceManager.GetString("HeThongThongBaoThoiGianDenBeHonThoiGianTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% ....
        /// </summary>
        internal static string HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong {
            get {
                return ResourceManager.GetString("HeThongThongBaoTienDoHoanThanhTaiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogForm {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting {
            get {
                return ResourceManager.GetString("HeThongThongBaoTieuDeChoWaitDialogFormIsPleaseWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a password.
        /// </summary>
        internal static string NguoiDungChuaNhapMatKhauDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapMatKhauDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not signed up yet.
        /// </summary>
        internal static string NguoiDungChuaNhapTaiKhoanDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungChuaNhapTaiKhoanDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is incorrect.
        /// </summary>
        internal static string NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac {
            get {
                return ResourceManager.GetString("NguoiDungDoiMatKhauMatKhauXacNhanKhongChinhXac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string NguoiDungNhapDuLieuKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapDuLieuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year is invalid, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapNamKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birth year, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapNamSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNamSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapNgayKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time must be greater than current date.
        /// </summary>
        internal static string NguoiDungNhapNgayPhaiNhoHonNgayHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgayPhaiNhoHonNgayHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is invalid, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days old must be smaller than the current date.
        /// </summary>
        internal static string NguoiDungNhapNgaySinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapNgaySinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been configured into the study, please contact your system administrator for assistance..
        /// </summary>
        internal static string NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungChuaDuocCauHinhVaoPhongLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are configured to work in the room but not in the room that is granted, please select a different room or check the software configuration..
        /// </summary>
        internal static string NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHinh {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungDuocCauHinhVaoPhongKhongDuocGanQuyenVuiLongKiemTraLaiCauHin" +
                        "h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are not authorized to work in the room, please contact your system administrator for assistance.
        /// </summary>
        internal static string NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong {
            get {
                return ResourceManager.GetString("NguoiDungNhapNguoiDungKhongDuocGanQuyenVaoPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes began collecting detailed records must be an integer value in the range of 1 to 1,000,000,000.
        /// </summary>
        internal static string NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapPhieuTuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes must be an integer value between 0 to 1 billion.
        /// </summary>
        internal static string NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapSoPhieuDeTaoPhieuThuChiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or password is incorrect.
        /// </summary>
        internal static string NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap {
            get {
                return ResourceManager.GetString("NguoiDungNhapTaiKhoanHoacMatKhauKhongChinhXacDeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May invalid, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapThangKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth month is invalid, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapThangSinhKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months must be less than the current date.
        /// </summary>
        internal static string NguoiDungNhapThangSinhLonHonHienTai {
            get {
                return ResourceManager.GetString("NguoiDungNhapThangSinhLonHonHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is invalid, please re-enter.
        /// </summary>
        internal static string NguoiDungNhapTuoiBenhNhanKhongHopLe {
            get {
                return ResourceManager.GetString("NguoiDungNhapTuoiBenhNhanKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software can not connect to the server system. Please check the configuration and connectivity.
        /// </summary>
        internal static string PhanMemKhongKetNoiDuocToiMayChuHeThong {
            get {
                return ResourceManager.GetString("PhanMemKhongKetNoiDuocToiMayChuHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown number.
        /// </summary>
        internal static string SuaChiDinhDichVu_KhongCoDoiSoLuong {
            get {
                return ResourceManager.GetString("SuaChiDinhDichVu_KhongCoDoiSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account no right to perform functions.
        /// </summary>
        internal static string TaiKhoanKhongCoQuyenThucHienChucNang {
            get {
                return ResourceManager.GetString("TaiKhoanKhongCoQuyenThucHienChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of data fields required.
        /// </summary>
        internal static string ThieuTruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("ThieuTruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string ThongBaoDuLieuTrong {
            get {
                return ResourceManager.GetString("ThongBaoDuLieuTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found when patients via card swipe reader npc, card code {0}.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanKhiQuetTheDuLieuTraVeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform patients of search results.
        /// </summary>
        internal static string ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua {
            get {
                return ResourceManager.GetString("ThongBaoKetQuaTimKiemBenhNhanTraVeCoDuLieuBanCoMuonSuDungKetQua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaCanhBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaLoi {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string TieuDeCuaSoThongBaoLaThongBao {
            get {
                return ResourceManager.GetString("TieuDeCuaSoThongBaoLaThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string TieuDeThongTinHienThiPhanTrang {
            get {
                return ResourceManager.GetString("TieuDeThongTinHienThiPhanTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields.
        /// </summary>
        internal static string TruongDuLieuBatBuoc {
            get {
                return ResourceManager.GetString("TruongDuLieuBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile of treatment has ended.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_HoSoDieuTriDangDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the person who created this request.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungNguoiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current room is not specified room service.
        /// </summary>
        internal static string XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau {
            get {
                return ResourceManager.GetString("XoaYeuCauChiDinhDichVu_KhongDungPhongYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not choose medicine and supplies to pay.
        /// </summary>
        internal static string XuatTraThuoc_ChuaChonThuocVatTuDeTra {
            get {
                return ResourceManager.GetString("XuatTraThuoc_ChuaChonThuocVatTuDeTra", resourceCulture);
            }
        }
    }
}
