/* IVT
 * @Project : hisnguonmo
 * Copyright (C) 2017 INVENTEC
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.UC.Login.Label {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextLabelViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextLabelViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventec.UC.Login.Label.TextLabelViResource", typeof(TextLabelViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_BTN_CONFIG {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_BTN_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_BTN_EXIT {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_BTN_LOGIN {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động đăng nhập.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_CHK_AUTO_LOGIN {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_CHK_AUTO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_FRM_LOGIN {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_FRM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản:.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_LBL_ACCOUNT {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_LBL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_LBL_BRANCH {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_LBL_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_LBL_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_LBL_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ:.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_LBL_LANGUAGE {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_LBL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu:.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải cấu hình hệ thống.
        /// </summary>
        internal static string IVT_LANGUAGE_KEY_FRMLOGIN_PROGRESS_LOADING {
            get {
                return ResourceManager.GetString("IVT_LANGUAGE_KEY_FRMLOGIN_PROGRESS_LOADING", resourceCulture);
            }
        }
    }
}
